# meta
# seed is handled by the spawner
# uuid is handled by the spawner (and otherwise one is created later)

# resources
cuda: true
fp16: true

# logging
wandb_project: 'cubone'

# dataset
dataset_handle: 'bigearthnet'
# data path is handled by the spawner w/ an environ variable
val_split: 0.25
test_split: 0.25
num_workers: 4

# training
epochs: -1
batch_size: 128
save_freq: 1
eval_every: 16

# opt
lr: 3e-4
wd: 0
clip_norm: 0
acc_grad_steps: 8
lars: true
sched: true

# algorithm choice
algo_handle: 'simclr'

# model architecture
backbone: 'resnet101'
pretrained_w_imagenet: false
fc_hid_dim: 128
fc_out_dim: 64

# algorithm
ntx_temp: 0.07

# fine-tuning or linear probing
load_checkpoint: 'model_10_done.tar'
linear_probe: true
fine_tuning: false
ftop_epochs: 90
ftop_batch_size: 128

