# meta
task: 'train'
# seed is handled by the spawner
# uuid is handled by the spawner (and otherwise one is created later)

# resources
cuda: true
fp16: true

# logging
wandb_project: 'cubone'

# dataset
dataset_handle: 'bigearthnet'
# data path is handled by the spawner w/ an environ variable
val_split: 0.25
test_split: 0.25
num_workers: 4

# training
epochs: -1
batch_size: 128
save_freq: 1

# opt
lr: 1.0
wd: 0
clip_norm: 0

# algo
algo_handle: 'bigearthnet_simclr'

# model architecture
backbone: 'resnet101'
pretrained_w_imagenet: true
fc_hid_dim: 128
fc_out_dim: 64

# fine-tuning or linear probing
load_checkpoint: 'model_3_done.tar'
linear_probe: true
fine_tuning: false
finetune_probe_epochs: 90
finetune_probe_batch_size: 128
