# meta
# seed is handled by the spawner
# uuid is handled by the spawner (and otherwise one is created later)

# resources
cuda: true
fp16: true

# logging
wandb_project: 'winter'

# dataset
dataset_handle: 'bigearthnet'
# data path is handled by the spawner w/ an environ variable
num_workers: 0 # 0: no parallelism in dataloader, PyTorch bug

# training
epochs: 10
batch_size: 128
save_freq: 1
eval_every: 600

# opt
lr: 3e-4
wd: 1e-4
clip_norm: 0
acc_grad_steps: 8
lars: true
sched: true

# algorithm choice
algo_handle: 'simclr'

# model architecture
backbone: 'resnet101'
pretrained_w_imagenet: true
fc_hid_dim: 128
fc_out_dim: 64

# algorithm
ntx_temp: 0.07

# fine-tuning or linear probing
num_classes: 19
linear_probe: false
fine_tuning: false
ftop_epochs: 50
ftop_batch_size: 128

