# meta
task: 'train'
# seed is handled by the spawner
# uuid is handled by the spawner (and otherwise one is created later)

# resources
cuda: true
fp16: false

# logging
wandb_project: 'charizard'

# dataset
dataset_handle: 'bigearthnet'
# data path is handled by the spawner w/ an environ variable
val_split: 0.25
test_split: 0.25

# training
epochs: 100
batch_size: 512
save_freq: 1

# opt
lr: 3e-4
wd: 2e-5
clip_norm: 0

# algo
algo_handle: 'bigearthnet_classifier'

# model architecture
backbone: 'resnet101'
pretrained_w_imagenet: true
fc_hid_dim: 128
