# meta
task: 'train'
# seed is handled by the spawner
# uuid is handled by the spawner (and otherwise one is created later)

# resources
cuda: true
fp16: false

# logging
wandb_project: 'sapphire'

# dataset
dataset_handle: 'bigearthnet'
# data path is handled by the spawner w/ an environ variable
val_split: 0.15
test_split: 0.15

# training
epochs: -1
batch_size: 128
save_freq: 1

# opt
lr: 3e-4
wd: 1e-6
clip_norm: 60.

# algo
algo_handle: 'bigearthnet_simclr'

# model architecture
backbone: 'resnet18'
pretrained_w_imagenet: true
fc_hid_dim: 128
fc_out_dim: 64

# fine-tuning or linear probing
load_checkpoint: 'model_3_done.tar'
linear_probe: false
fine_tuning: true
finetune_probe_epochs: 50
finetune_probe_batch_size: 256
